#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_REACTIVE_SIMPLE
// Enable RGB Matrix
#define VIA_QMK_RGBLIGHT_ENABLE

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define CAPS_LOCK_INDEX 29
#define NUM_LOCK_INDEX 14
#define EECONFIG_KB_DATA_SIZE 16
