#pragma once 
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_REACTIVE_SIMPLE;

#define DYNAMIC_KEYMAP_LAYER_COUNT 3

#define WEAR_LEVELING_SN32_EMULATION_PAGE_COUNT 36
#define VIA_QMK_RGBLIGHT_ENABLE

#define CAPS_LOCK_INDEX 57
#define NUM_LOCK_INDEX 33
#define EECONFIG_KB_DATA_SIZE 16

